### ISSUE TITLE
Docker setup fails

### ISSUE THREAD

**Issue by Kiszaner** [BrickWaterStudios/Julieanne#2]
After installing Docker, running the command `docker run --name postgres -e POSTGRES_DB=vapor \ -e POSTGRES_USER=vapor -e POSTGRES_PASSWORD=password \ -p 5432:5432 -d postgres` returns an error: `docker: invalid reference format.`
I attached a Terminal screenshot.
<img width="682" alt="Screen Shot 2019-09-13 at 19 00 17" src="https://user-images.githubusercontent.com/9079893/64881706-c7904680-d65b-11e9-9a4a-db09783e5920.png">

**Comment by BastianInuk** [comment]
What if you run this? 
```sh
docker run --name postgress -e POSTGRES_DB=vapor \
-e POSTGRES_USER=vaport \
-e POSTGRES_PASSWORD=password \
-p 5432:5432 \
-d postgres
```

**Comment by BastianInuk** [comment]
Alternatively, this should also work:
```sh
docker run \
--name postgress \
-e POSTGRES_DB=vapor \
-e POSTGRES_USER=vaport \
-e POSTGRES_PASSWORD=password \
-p 5432:5432 \
-d postgres
```

**Comment by BastianInuk** [comment]
If you are on the newest commit, then `docker-compose up` (or `docker-compose up -d` if you want it in the background) should do the trick!

**Comment by Kiszaner** [comment]
Solved with the docker compose command, thanks!
